# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(609, 420)
        self.moritz_pic = QtWidgets.QLabel(parent=About)
        self.moritz_pic.setGeometry(QtCore.QRect(20, 102, 120, 120))
        self.moritz_pic.setText("")
        self.moritz_pic.setPixmap(QtGui.QPixmap("img/moritz.jpg"))
        self.moritz_pic.setScaledContents(True)
        self.moritz_pic.setObjectName("moritz_pic")
        self.thor_pic = QtWidgets.QLabel(parent=About)
        self.thor_pic.setGeometry(QtCore.QRect(20, 267, 120, 120))
        self.thor_pic.setText("")
        self.thor_pic.setPixmap(QtGui.QPixmap("img/thor.jpg"))
        self.thor_pic.setScaledContents(True)
        self.thor_pic.setObjectName("thor_pic")
        self.header_panel = QtWidgets.QLabel(parent=About)
        self.header_panel.setGeometry(QtCore.QRect(-20, -20, 629, 89))
        self.header_panel.setStyleSheet("/* Rectangle 32 */\n"
"\n"
"position: absolute;\n"
"width: 629px;\n"
"height: 89px;\n"
"left: -20px;\n"
"top: -20px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 20px;\n"
"")
        self.header_panel.setText("")
        self.header_panel.setObjectName("header_panel")
        self.header_text = QtWidgets.QLabel(parent=About)
        self.header_text.setGeometry(QtCore.QRect(0, 0, 609, 69))
        self.header_text.setStyleSheet("/* About Us */\n"
"\n"
"position: absolute;\n"
"width: 609px;\n"
"height: 69px;\n"
"left: 0px;\n"
"top: 0px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 32px;\n"
"line-height: 40px;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.header_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header_text.setObjectName("header_text")
        self.moritz_panel = QtWidgets.QLabel(parent=About)
        self.moritz_panel.setGeometry(QtCore.QRect(-20, 102, 609, 120))
        self.moritz_panel.setStyleSheet("/* Rectangle 34 */\n"
"\n"
"position: absolute;\n"
"width: 609px;\n"
"height: 120px;\n"
"left: -20px;\n"
"top: 102px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 20px;\n"
"")
        self.moritz_panel.setText("")
        self.moritz_panel.setObjectName("moritz_panel")
        self.thor_panel = QtWidgets.QLabel(parent=About)
        self.thor_panel.setGeometry(QtCore.QRect(-20, 267, 609, 120))
        self.thor_panel.setStyleSheet("/* Rectangle 34 */\n"
"\n"
"position: absolute;\n"
"width: 609px;\n"
"height: 120px;\n"
"left: -20px;\n"
"top: 102px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 20px;\n"
"")
        self.thor_panel.setText("")
        self.thor_panel.setObjectName("thor_panel")
        self.moritz_header = QtWidgets.QLabel(parent=About)
        self.moritz_header.setGeometry(QtCore.QRect(160, 107, 409, 31))
        self.moritz_header.setStyleSheet("/* Moritz Jüttner */\n"
"\n"
"position: absolute;\n"
"width: 409px;\n"
"height: 31px;\n"
"left: 160px;\n"
"top: 107px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"display: flex;\n"
"align-items: center;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.moritz_header.setObjectName("moritz_header")
        self.thor_header = QtWidgets.QLabel(parent=About)
        self.thor_header.setGeometry(QtCore.QRect(160, 272, 409, 31))
        self.thor_header.setStyleSheet("/* Moritz Jüttner */\n"
"\n"
"position: absolute;\n"
"width: 409px;\n"
"height: 31px;\n"
"left: 160px;\n"
"top: 107px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 24px;\n"
"line-height: 30px;\n"
"display: flex;\n"
"align-items: center;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.thor_header.setObjectName("thor_header")
        self.moritz_desc = QtWidgets.QLabel(parent=About)
        self.moritz_desc.setGeometry(QtCore.QRect(160, 139, 409, 78))
        self.moritz_desc.setStyleSheet("/* Programmer Project Manager professional Procrastinator */\n"
"\n"
"position: absolute;\n"
"width: 409px;\n"
"height: 78px;\n"
"left: 160px;\n"
"top: 139px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"display: flex;\n"
"align-items: center;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.moritz_desc.setObjectName("moritz_desc")
        self.thor_desc = QtWidgets.QLabel(parent=About)
        self.thor_desc.setGeometry(QtCore.QRect(160, 304, 409, 78))
        self.thor_desc.setStyleSheet("/* Programmer Project Manager professional Procrastinator */\n"
"\n"
"position: absolute;\n"
"width: 409px;\n"
"height: 78px;\n"
"left: 160px;\n"
"top: 139px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"display: flex;\n"
"align-items: center;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.thor_desc.setObjectName("thor_desc")
        self.thor_panel.raise_()
        self.moritz_panel.raise_()
        self.moritz_pic.raise_()
        self.thor_pic.raise_()
        self.header_panel.raise_()
        self.header_text.raise_()
        self.moritz_header.raise_()
        self.thor_header.raise_()
        self.moritz_desc.raise_()
        self.thor_desc.raise_()

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About Us"))
        self.header_text.setText(_translate("About", "About Us"))
        self.moritz_header.setText(_translate("About", "Moritz Jüttner"))
        self.thor_header.setText(_translate("About", "Thor Poser"))
        self.moritz_desc.setText(_translate("About", "- Programmer\n"
"- Project Manager\n"
"- professional Procrastinator"))
        self.thor_desc.setText(_translate("About", "- Graphics\n"
"- Design\n"
"- Emotional Support"))
