# Form implementation generated from reading ui file 'creator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Creator(object):
    def setupUi(self, Creator):
        Creator.setObjectName("Creator")
        Creator.resize(400, 132)
        self.type_input = QtWidgets.QComboBox(parent=Creator)
        self.type_input.setGeometry(QtCore.QRect(10, 10, 381, 22))
        self.type_input.setObjectName("type_input")
        self.type_input.addItem("")
        self.type_input.addItem("")
        self.type_input.addItem("")
        self.name_input = QtWidgets.QLineEdit(parent=Creator)
        self.name_input.setGeometry(QtCore.QRect(10, 70, 381, 22))
        self.name_input.setObjectName("name_input")
        self.gen_button = QtWidgets.QPushButton(parent=Creator)
        self.gen_button.setGeometry(QtCore.QRect(10, 100, 381, 24))
        self.gen_button.setObjectName("gen_button")
        self.subject_input = QtWidgets.QLineEdit(parent=Creator)
        self.subject_input.setGeometry(QtCore.QRect(10, 40, 381, 22))
        self.subject_input.setObjectName("subject_input")

        self.retranslateUi(Creator)
        QtCore.QMetaObject.connectSlotsByName(Creator)

    def retranslateUi(self, Creator):
        _translate = QtCore.QCoreApplication.translate
        Creator.setWindowTitle(_translate("Creator", "Set Creator"))
        self.type_input.setItemText(0, _translate("Creator", "Text to Text"))
        self.type_input.setItemText(1, _translate("Creator", "Text to Image"))
        self.type_input.setItemText(2, _translate("Creator", "Gap-Text"))
        self.name_input.setPlaceholderText(_translate("Creator", "Choose Name"))
        self.gen_button.setText(_translate("Creator", "Create"))
        self.subject_input.setPlaceholderText(_translate("Creator", "Choose Subject"))
