# Form implementation generated from reading ui file 'Definitions.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Definitions(object):
    def setupUi(self, Definitions):
        Definitions.setObjectName("Definitions")
        Definitions.resize(720, 250)
        self.header = QtWidgets.QLabel(parent=Definitions)
        self.header.setGeometry(QtCore.QRect(0, 10, 720, 60))
        self.header.setObjectName("header")
        self.def1_button = QtWidgets.QPushButton(parent=Definitions)
        self.def1_button.setGeometry(QtCore.QRect(20, 100, 400, 30))
        self.def1_button.setToolTipDuration(10)
        self.def1_button.setCheckable(True)
        self.def1_button.setObjectName("def1_button")
        self.def2_button = QtWidgets.QPushButton(parent=Definitions)
        self.def2_button.setGeometry(QtCore.QRect(20, 150, 400, 30))
        self.def2_button.setToolTipDuration(10)
        self.def2_button.setCheckable(True)
        self.def2_button.setObjectName("def2_button")
        self.def3_button = QtWidgets.QPushButton(parent=Definitions)
        self.def3_button.setGeometry(QtCore.QRect(20, 200, 400, 30))
        self.def3_button.setToolTipDuration(10)
        self.def3_button.setCheckable(True)
        self.def3_button.setObjectName("def3_button")
        self.term1_button = QtWidgets.QPushButton(parent=Definitions)
        self.term1_button.setGeometry(QtCore.QRect(500, 100, 200, 30))
        self.term1_button.setToolTipDuration(10)
        self.term1_button.setCheckable(True)
        self.term1_button.setObjectName("term1_button")
        self.term2_button = QtWidgets.QPushButton(parent=Definitions)
        self.term2_button.setGeometry(QtCore.QRect(500, 150, 200, 30))
        self.term2_button.setToolTipDuration(10)
        self.term2_button.setCheckable(True)
        self.term2_button.setObjectName("term2_button")
        self.term3_button = QtWidgets.QPushButton(parent=Definitions)
        self.term3_button.setGeometry(QtCore.QRect(500, 200, 200, 30))
        self.term3_button.setToolTipDuration(10)
        self.term3_button.setCheckable(True)
        self.term3_button.setObjectName("term3_button")
        self.term1_button.raise_()
        self.header.raise_()
        self.def1_button.raise_()
        self.def2_button.raise_()
        self.def3_button.raise_()
        self.term2_button.raise_()
        self.term3_button.raise_()

        self.retranslateUi(Definitions)
        QtCore.QMetaObject.connectSlotsByName(Definitions)

    def retranslateUi(self, Definitions):
        _translate = QtCore.QCoreApplication.translate
        Definitions.setWindowTitle(_translate("Definitions", "Definitions"))
        self.header.setText(_translate("Definitions", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">Definitions</span></p><p align=\"center\">Connect the definition to its term</p><p align=\"center\"><br/></p></body></html>"))
        self.def1_button.setText(_translate("Definitions", "Definition 1"))
        self.def2_button.setText(_translate("Definitions", "Definition 2"))
        self.def3_button.setText(_translate("Definitions", "Definition 3"))
        self.term1_button.setText(_translate("Definitions", "Term 1"))
        self.term2_button.setText(_translate("Definitions", "Term 2"))
        self.term3_button.setText(_translate("Definitions", "Term 3"))
