# Form implementation generated from reading ui file 'Definitions.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Definitions(object):
    def setupUi(self, Definitions):
        Definitions.setObjectName("Definitions")
        Definitions.resize(1200, 530)
        self.header = QtWidgets.QLabel(parent=Definitions)
        self.header.setGeometry(QtCore.QRect(10, 0, 320, 70))
        self.header.setStyleSheet("/* Definitions to Terms */\n"
"\n"
"position: absolute;\n"
"width: 320px;\n"
"height: 70px;\n"
"left: 10px;\n"
"top: 0px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 32px;\n"
"line-height: 40px;\n"
"display: flex;\n"
"align-items: center;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.header.setObjectName("header")
        self.def1_button = QtWidgets.QPushButton(parent=Definitions)
        self.def1_button.setGeometry(QtCore.QRect(15, 148, 570, 80))
        self.def1_button.setToolTipDuration(10)
        self.def1_button.setText("")
        self.def1_button.setCheckable(True)
        self.def1_button.setFlat(True)
        self.def1_button.setObjectName("def1_button")
        self.def2_button = QtWidgets.QPushButton(parent=Definitions)
        self.def2_button.setGeometry(QtCore.QRect(15, 260, 570, 80))
        self.def2_button.setToolTipDuration(10)
        self.def2_button.setText("")
        self.def2_button.setCheckable(True)
        self.def2_button.setFlat(True)
        self.def2_button.setObjectName("def2_button")
        self.def3_button = QtWidgets.QPushButton(parent=Definitions)
        self.def3_button.setGeometry(QtCore.QRect(15, 372, 570, 80))
        self.def3_button.setToolTipDuration(10)
        self.def3_button.setText("")
        self.def3_button.setCheckable(True)
        self.def3_button.setFlat(True)
        self.def3_button.setObjectName("def3_button")
        self.term1_button = QtWidgets.QPushButton(parent=Definitions)
        self.term1_button.setGeometry(QtCore.QRect(815, 148, 370, 80))
        self.term1_button.setToolTipDuration(10)
        self.term1_button.setText("")
        self.term1_button.setCheckable(True)
        self.term1_button.setFlat(True)
        self.term1_button.setObjectName("term1_button")
        self.term2_button = QtWidgets.QPushButton(parent=Definitions)
        self.term2_button.setGeometry(QtCore.QRect(815, 260, 370, 80))
        self.term2_button.setToolTipDuration(10)
        self.term2_button.setText("")
        self.term2_button.setCheckable(True)
        self.term2_button.setFlat(True)
        self.term2_button.setObjectName("term2_button")
        self.term3_button = QtWidgets.QPushButton(parent=Definitions)
        self.term3_button.setGeometry(QtCore.QRect(815, 372, 370, 80))
        self.term3_button.setToolTipDuration(10)
        self.term3_button.setText("")
        self.term3_button.setCheckable(True)
        self.term3_button.setFlat(True)
        self.term3_button.setObjectName("term3_button")
        self.header_panel = QtWidgets.QLabel(parent=Definitions)
        self.header_panel.setGeometry(QtCore.QRect(-30, -30, 1230, 100))
        self.header_panel.setStyleSheet("background: #56855E;\n"
"border-radius: 30px;\n"
"")
        self.header_panel.setText("")
        self.header_panel.setObjectName("header_panel")
        self.description = QtWidgets.QLabel(parent=Definitions)
        self.description.setGeometry(QtCore.QRect(330, 34, 394, 12))
        self.description.setStyleSheet("/* Connect the definitions to the corresponding terms. */\n"
"\n"
"position: absolute;\n"
"width: 394px;\n"
"height: 12px;\n"
"left: 330px;\n"
"top: 36px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"display: flex;\n"
"align-items: center;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.description.setObjectName("description")
        self.def1_panel = QtWidgets.QLabel(parent=Definitions)
        self.def1_panel.setGeometry(QtCore.QRect(-15, 148, 615, 80))
        self.def1_panel.setStyleSheet("/* Rectangle 21 */\n"
"\n"
"position: absolute;\n"
"width: 615px;\n"
"height: 80px;\n"
"left: -15px;\n"
"top: 148px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 15px;\n"
"")
        self.def1_panel.setText("")
        self.def1_panel.setObjectName("def1_panel")
        self.def2_panel = QtWidgets.QLabel(parent=Definitions)
        self.def2_panel.setGeometry(QtCore.QRect(-15, 260, 615, 80))
        self.def2_panel.setStyleSheet("/* Rectangle 21 */\n"
"\n"
"position: absolute;\n"
"width: 615px;\n"
"height: 80px;\n"
"left: -15px;\n"
"top: 148px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 15px;\n"
"")
        self.def2_panel.setText("")
        self.def2_panel.setObjectName("def2_panel")
        self.def3_panel = QtWidgets.QLabel(parent=Definitions)
        self.def3_panel.setGeometry(QtCore.QRect(-15, 372, 615, 80))
        self.def3_panel.setStyleSheet("/* Rectangle 21 */\n"
"\n"
"position: absolute;\n"
"width: 615px;\n"
"height: 80px;\n"
"left: -15px;\n"
"top: 148px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 15px;\n"
"")
        self.def3_panel.setText("")
        self.def3_panel.setObjectName("def3_panel")
        self.def1_text = QtWidgets.QLabel(parent=Definitions)
        self.def1_text.setGeometry(QtCore.QRect(15, 148, 570, 80))
        self.def1_text.setStyleSheet("/* Definition 1 */\n"
"\n"
"position: absolute;\n"
"width: 570px;\n"
"height: 80px;\n"
"left: 15px;\n"
"top: 148px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 32px;\n"
"line-height: 40px;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: right;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.def1_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.def1_text.setObjectName("def1_text")
        self.def2_text = QtWidgets.QLabel(parent=Definitions)
        self.def2_text.setGeometry(QtCore.QRect(15, 260, 570, 80))
        self.def2_text.setStyleSheet("/* Definition 1 */\n"
"\n"
"position: absolute;\n"
"width: 570px;\n"
"height: 80px;\n"
"left: 15px;\n"
"top: 148px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 32px;\n"
"line-height: 40px;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: right;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.def2_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.def2_text.setObjectName("def2_text")
        self.def3_text = QtWidgets.QLabel(parent=Definitions)
        self.def3_text.setGeometry(QtCore.QRect(15, 375, 570, 80))
        self.def3_text.setStyleSheet("/* Definition 1 */\n"
"\n"
"position: absolute;\n"
"width: 570px;\n"
"height: 80px;\n"
"left: 15px;\n"
"top: 148px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 32px;\n"
"line-height: 40px;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: right;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.def3_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.def3_text.setObjectName("def3_text")
        self.term1_panel = QtWidgets.QLabel(parent=Definitions)
        self.term1_panel.setGeometry(QtCore.QRect(800, 148, 415, 80))
        self.term1_panel.setStyleSheet("/* Rectangle 24 */\n"
"\n"
"position: absolute;\n"
"width: 415px;\n"
"height: 80px;\n"
"left: 800px;\n"
"top: 148px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 15px;\n"
"")
        self.term1_panel.setText("")
        self.term1_panel.setObjectName("term1_panel")
        self.term2_panel = QtWidgets.QLabel(parent=Definitions)
        self.term2_panel.setGeometry(QtCore.QRect(800, 260, 415, 80))
        self.term2_panel.setStyleSheet("/* Rectangle 24 */\n"
"\n"
"position: absolute;\n"
"width: 415px;\n"
"height: 80px;\n"
"left: 800px;\n"
"top: 148px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 15px;\n"
"")
        self.term2_panel.setText("")
        self.term2_panel.setObjectName("term2_panel")
        self.term3_panel = QtWidgets.QLabel(parent=Definitions)
        self.term3_panel.setGeometry(QtCore.QRect(800, 372, 415, 80))
        self.term3_panel.setStyleSheet("/* Rectangle 24 */\n"
"\n"
"position: absolute;\n"
"width: 415px;\n"
"height: 80px;\n"
"left: 800px;\n"
"top: 148px;\n"
"\n"
"background: #56855E;\n"
"border-radius: 15px;\n"
"")
        self.term3_panel.setText("")
        self.term3_panel.setObjectName("term3_panel")
        self.term1_text = QtWidgets.QLabel(parent=Definitions)
        self.term1_text.setGeometry(QtCore.QRect(815, 148, 370, 80))
        self.term1_text.setStyleSheet("/* Definition 1 */\n"
"\n"
"position: absolute;\n"
"width: 570px;\n"
"height: 80px;\n"
"left: 15px;\n"
"top: 148px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 32px;\n"
"line-height: 40px;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: right;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.term1_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.term1_text.setObjectName("term1_text")
        self.term2_text = QtWidgets.QLabel(parent=Definitions)
        self.term2_text.setGeometry(QtCore.QRect(815, 260, 370, 80))
        self.term2_text.setStyleSheet("/* Definition 1 */\n"
"\n"
"position: absolute;\n"
"width: 570px;\n"
"height: 80px;\n"
"left: 15px;\n"
"top: 148px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 32px;\n"
"line-height: 40px;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: right;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.term2_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.term2_text.setObjectName("term2_text")
        self.term3_text = QtWidgets.QLabel(parent=Definitions)
        self.term3_text.setGeometry(QtCore.QRect(815, 372, 370, 80))
        self.term3_text.setStyleSheet("/* Definition 1 */\n"
"\n"
"position: absolute;\n"
"width: 570px;\n"
"height: 80px;\n"
"left: 15px;\n"
"top: 148px;\n"
"\n"
"font-family: \'Atkinson Hyperlegible\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 32px;\n"
"line-height: 40px;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: right;\n"
"\n"
"color: #E3DBA4;\n"
"\n"
"")
        self.term3_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.term3_text.setObjectName("term3_text")
        self.header_panel.raise_()
        self.header.raise_()
        self.description.raise_()
        self.def1_panel.raise_()
        self.def2_panel.raise_()
        self.def3_panel.raise_()
        self.def1_text.raise_()
        self.def2_text.raise_()
        self.def3_text.raise_()
        self.def2_button.raise_()
        self.def1_button.raise_()
        self.def3_button.raise_()
        self.term1_panel.raise_()
        self.term2_panel.raise_()
        self.term3_panel.raise_()
        self.term1_text.raise_()
        self.term2_text.raise_()
        self.term3_text.raise_()
        self.term1_button.raise_()
        self.term2_button.raise_()
        self.term3_button.raise_()

        self.retranslateUi(Definitions)
        QtCore.QMetaObject.connectSlotsByName(Definitions)

    def retranslateUi(self, Definitions):
        _translate = QtCore.QCoreApplication.translate
        Definitions.setWindowTitle(_translate("Definitions", "Definitions"))
        self.header.setText(_translate("Definitions", "<html><head/><body><p>Definitions to Terms</p></body></html>"))
        self.description.setText(_translate("Definitions", "Connect the definitions to the corresponding terms."))
        self.def1_text.setText(_translate("Definitions", "Definition 1"))
        self.def2_text.setText(_translate("Definitions", "Definition 2"))
        self.def3_text.setText(_translate("Definitions", "Definition 3"))
        self.term1_text.setText(_translate("Definitions", "Term 1"))
        self.term2_text.setText(_translate("Definitions", "Term 2"))
        self.term3_text.setText(_translate("Definitions", "Term 3"))
