# Form implementation generated from reading ui file 'editor_Director.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Set_Creator_Director(object):
    def setupUi(self, Set_Creator_Director):
        Set_Creator_Director.setObjectName("Set_Creator_Director")
        Set_Creator_Director.resize(313, 181)
        self.Add_T2T_Button = QtWidgets.QPushButton(parent=Set_Creator_Director)
        self.Add_T2T_Button.setGeometry(QtCore.QRect(30, 40, 251, 24))
        self.Add_T2T_Button.setObjectName("Add_T2T_Button")
        self.Add_LText_Button = QtWidgets.QPushButton(parent=Set_Creator_Director)
        self.Add_LText_Button.setGeometry(QtCore.QRect(30, 120, 251, 24))
        self.Add_LText_Button.setObjectName("Add_LText_Button")
        self.Add_T2I_Button = QtWidgets.QPushButton(parent=Set_Creator_Director)
        self.Add_T2I_Button.setGeometry(QtCore.QRect(30, 80, 251, 24))
        self.Add_T2I_Button.setObjectName("Add_T2I_Button")

        self.retranslateUi(Set_Creator_Director)
        QtCore.QMetaObject.connectSlotsByName(Set_Creator_Director)

    def retranslateUi(self, Set_Creator_Director):
        _translate = QtCore.QCoreApplication.translate
        Set_Creator_Director.setWindowTitle(_translate("Set_Creator_Director", "Art des hinzugefügten Sets auswählen"))
        self.Add_T2T_Button.setText(_translate("Set_Creator_Director", "Begriff-zu-Definition hinzufügen"))
        self.Add_LText_Button.setText(_translate("Set_Creator_Director", "Lückentext hinzufügen"))
        self.Add_T2I_Button.setText(_translate("Set_Creator_Director", "Begriff-zu-Bild hinzufügen"))
