# Form implementation generated from reading ui file 'editor_LText.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Set_Creator_LText(object):
    def setupUi(self, Set_Creator_LText):
        Set_Creator_LText.setObjectName("Set_Creator_LText")
        Set_Creator_LText.resize(500, 460)
        self.save_button = QtWidgets.QPushButton(parent=Set_Creator_LText)
        self.save_button.setGeometry(QtCore.QRect(10, 420, 481, 31))
        self.save_button.setObjectName("save_button")
        self.text_area = QtWidgets.QTextEdit(parent=Set_Creator_LText)
        self.text_area.setGeometry(QtCore.QRect(10, 10, 480, 400))
        self.text_area.setObjectName("text_area")

        self.retranslateUi(Set_Creator_LText)
        QtCore.QMetaObject.connectSlotsByName(Set_Creator_LText)

    def retranslateUi(self, Set_Creator_LText):
        _translate = QtCore.QCoreApplication.translate
        Set_Creator_LText.setWindowTitle(_translate("Set_Creator_LText", "Gap-Text Editor"))
        self.save_button.setText(_translate("Set_Creator_LText", "Save"))
