# Form implementation generated from reading ui file 'editor_T2T.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Set_Creator_T2T(object):
    def setupUi(self, Set_Creator_T2T):
        Set_Creator_T2T.setObjectName("Set_Creator_T2T")
        Set_Creator_T2T.resize(500, 460)
        self.save_button = QtWidgets.QPushButton(parent=Set_Creator_T2T)
        self.save_button.setGeometry(QtCore.QRect(10, 420, 481, 31))
        self.save_button.setObjectName("save_button")
        self.text_area = QtWidgets.QTextEdit(parent=Set_Creator_T2T)
        self.text_area.setGeometry(QtCore.QRect(10, 10, 480, 400))
        self.text_area.setObjectName("text_area")

        self.retranslateUi(Set_Creator_T2T)
        QtCore.QMetaObject.connectSlotsByName(Set_Creator_T2T)

    def retranslateUi(self, Set_Creator_T2T):
        _translate = QtCore.QCoreApplication.translate
        Set_Creator_T2T.setWindowTitle(_translate("Set_Creator_T2T", "T2T Editor"))
        self.save_button.setText(_translate("Set_Creator_T2T", "Save"))
