# Form implementation generated from reading ui file 'editor_T2I.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Set_Creator_T2I(object):
    def setupUi(self, Set_Creator_T2I):
        Set_Creator_T2I.setObjectName("Set_Creator_T2I")
        Set_Creator_T2I.resize(500, 460)
        self.text_area = QtWidgets.QTextEdit(parent=Set_Creator_T2I)
        self.text_area.setGeometry(QtCore.QRect(10, 10, 480, 400))
        self.text_area.setObjectName("text_area")
        self.save_button = QtWidgets.QPushButton(parent=Set_Creator_T2I)
        self.save_button.setGeometry(QtCore.QRect(10, 420, 481, 31))
        self.save_button.setObjectName("save_button")

        self.retranslateUi(Set_Creator_T2I)
        QtCore.QMetaObject.connectSlotsByName(Set_Creator_T2I)

    def retranslateUi(self, Set_Creator_T2I):
        _translate = QtCore.QCoreApplication.translate
        Set_Creator_T2I.setWindowTitle(_translate("Set_Creator_T2I", "T2I Editor"))
        self.save_button.setText(_translate("Set_Creator_T2I", "Save"))
