# Form implementation generated from reading ui file 'LText.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LText(object):
    def setupUi(self, LText):
        LText.setObjectName("LText")
        LText.resize(510, 283)
        self.text_area = QtWidgets.QTextEdit(parent=LText)
        self.text_area.setGeometry(QtCore.QRect(10, 10, 491, 171))
        self.text_area.setReadOnly(True)
        self.text_area.setObjectName("text_area")
        self.words_input = QtWidgets.QLineEdit(parent=LText)
        self.words_input.setGeometry(QtCore.QRect(10, 210, 491, 22))
        self.words_input.setObjectName("words_input")
        self.check_button = QtWidgets.QPushButton(parent=LText)
        self.check_button.setGeometry(QtCore.QRect(10, 250, 491, 24))
        self.check_button.setObjectName("check_button")

        self.retranslateUi(LText)
        QtCore.QMetaObject.connectSlotsByName(LText)

    def retranslateUi(self, LText):
        _translate = QtCore.QCoreApplication.translate
        LText.setWindowTitle(_translate("LText", "Gap Text"))
        self.text_area.setHtml(_translate("LText", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.check_button.setText(_translate("LText", "Check"))
