# Form implementation generated from reading ui file 'Open_Type.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Open_Type(object):
    def setupUi(self, Open_Type):
        Open_Type.setObjectName("Open_Type")
        Open_Type.resize(400, 342)
        self.header = QtWidgets.QLabel(parent=Open_Type)
        self.header.setGeometry(QtCore.QRect(0, 10, 400, 60))
        self.header.setObjectName("header")
        self.T2T_Button = QtWidgets.QPushButton(parent=Open_Type)
        self.T2T_Button.setGeometry(QtCore.QRect(50, 108, 300, 40))
        self.T2T_Button.setObjectName("T2T_Button")
        self.P2T_Button = QtWidgets.QPushButton(parent=Open_Type)
        self.P2T_Button.setGeometry(QtCore.QRect(50, 186, 300, 40))
        self.P2T_Button.setObjectName("P2T_Button")
        self.LText_Button = QtWidgets.QPushButton(parent=Open_Type)
        self.LText_Button.setGeometry(QtCore.QRect(50, 264, 300, 40))
        self.LText_Button.setObjectName("LText_Button")

        self.retranslateUi(Open_Type)
        QtCore.QMetaObject.connectSlotsByName(Open_Type)

    def retranslateUi(self, Open_Type):
        _translate = QtCore.QCoreApplication.translate
        Open_Type.setWindowTitle(_translate("Open_Type", "Practise Type"))
        self.header.setText(_translate("Open_Type", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">Practise Type</span></p></body></html>"))
        self.T2T_Button.setText(_translate("Open_Type", "Text and Definition"))
        self.P2T_Button.setText(_translate("Open_Type", "Picture and Definiton"))
        self.LText_Button.setText(_translate("Open_Type", "Gap Text"))
