# Form implementation generated from reading ui file 'Pictures.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Pictures(object):
    def setupUi(self, Pictures):
        Pictures.setObjectName("Pictures")
        Pictures.resize(720, 407)
        self.header = QtWidgets.QLabel(parent=Pictures)
        self.header.setGeometry(QtCore.QRect(0, 10, 720, 60))
        self.header.setObjectName("header")
        self.pic1_label = QtWidgets.QLabel(parent=Pictures)
        self.pic1_label.setGeometry(QtCore.QRect(110, 79, 100, 100))
        self.pic1_label.setText("")
        self.pic1_label.setScaledContents(True)
        self.pic1_label.setObjectName("pic1_label")
        self.pic2_label = QtWidgets.QLabel(parent=Pictures)
        self.pic2_label.setGeometry(QtCore.QRect(110, 188, 100, 100))
        self.pic2_label.setText("")
        self.pic2_label.setScaledContents(True)
        self.pic2_label.setObjectName("pic2_label")
        self.pic3_label = QtWidgets.QLabel(parent=Pictures)
        self.pic3_label.setGeometry(QtCore.QRect(110, 297, 100, 100))
        self.pic3_label.setText("")
        self.pic3_label.setScaledContents(True)
        self.pic3_label.setObjectName("pic3_label")
        self.term1_button = QtWidgets.QPushButton(parent=Pictures)
        self.term1_button.setGeometry(QtCore.QRect(410, 104, 200, 50))
        self.term1_button.setToolTipDuration(10)
        self.term1_button.setCheckable(True)
        self.term1_button.setObjectName("term1_button")
        self.term2_button = QtWidgets.QPushButton(parent=Pictures)
        self.term2_button.setGeometry(QtCore.QRect(410, 213, 200, 50))
        self.term2_button.setToolTipDuration(10)
        self.term2_button.setCheckable(True)
        self.term2_button.setObjectName("term2_button")
        self.term3_button = QtWidgets.QPushButton(parent=Pictures)
        self.term3_button.setGeometry(QtCore.QRect(410, 322, 200, 50))
        self.term3_button.setToolTipDuration(10)
        self.term3_button.setCheckable(True)
        self.term3_button.setObjectName("term3_button")

        self.retranslateUi(Pictures)
        QtCore.QMetaObject.connectSlotsByName(Pictures)

    def retranslateUi(self, Pictures):
        _translate = QtCore.QCoreApplication.translate
        Pictures.setWindowTitle(_translate("Pictures", "Pictures"))
        self.header.setText(_translate("Pictures", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">Pictures</span></p><p align=\"center\">Connect the picture to its term</p><p align=\"center\"><br/></p></body></html>"))
        self.term1_button.setText(_translate("Pictures", "Term 1"))
        self.term2_button.setText(_translate("Pictures", "Term 1"))
        self.term3_button.setText(_translate("Pictures", "Term 1"))
