# Form implementation generated from reading ui file 'Set_Creator_T2T.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Set_Creator_T2T(object):
    def setupUi(self, Set_Creator_T2T):
        Set_Creator_T2T.setObjectName("Set_Creator_T2T")
        Set_Creator_T2T.resize(402, 459)
        self.Term_Edit = QtWidgets.QLineEdit(parent=Set_Creator_T2T)
        self.Term_Edit.setGeometry(QtCore.QRect(100, 40, 201, 22))
        self.Term_Edit.setObjectName("Term_Edit")
        self.Def_Edit = QtWidgets.QLineEdit(parent=Set_Creator_T2T)
        self.Def_Edit.setGeometry(QtCore.QRect(100, 110, 201, 22))
        self.Def_Edit.setObjectName("Def_Edit")
        self.Term_Label = QtWidgets.QLabel(parent=Set_Creator_T2T)
        self.Term_Label.setGeometry(QtCore.QRect(100, 20, 49, 16))
        self.Term_Label.setObjectName("Term_Label")
        self.Def_Label = QtWidgets.QLabel(parent=Set_Creator_T2T)
        self.Def_Label.setGeometry(QtCore.QRect(100, 90, 71, 16))
        self.Def_Label.setObjectName("Def_Label")
        self.Pairs_scrollArea = QtWidgets.QScrollArea(parent=Set_Creator_T2T)
        self.Pairs_scrollArea.setGeometry(QtCore.QRect(20, 190, 361, 211))
        self.Pairs_scrollArea.setWidgetResizable(True)
        self.Pairs_scrollArea.setObjectName("Pairs_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Pairs_scrollBar = QtWidgets.QScrollBar(parent=self.scrollAreaWidgetContents)
        self.Pairs_scrollBar.setGeometry(QtCore.QRect(340, 0, 20, 191))
        self.Pairs_scrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.Pairs_scrollBar.setObjectName("Pairs_scrollBar")
        self.Pairs_ListWidget = QtWidgets.QListWidget(parent=self.scrollAreaWidgetContents)
        self.Pairs_ListWidget.setGeometry(QtCore.QRect(0, 0, 341, 211))
        self.Pairs_ListWidget.setObjectName("Pairs_ListWidget")
        self.Pairs_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Add_Pair_Button = QtWidgets.QPushButton(parent=Set_Creator_T2T)
        self.Add_Pair_Button.setGeometry(QtCore.QRect(120, 150, 81, 24))
        self.Add_Pair_Button.setObjectName("Add_Pair_Button")
        self.Close_Button = QtWidgets.QPushButton(parent=Set_Creator_T2T)
        self.Close_Button.setGeometry(QtCore.QRect(320, 420, 75, 24))
        self.Close_Button.setObjectName("Close_Button")
        self.Save_Button = QtWidgets.QPushButton(parent=Set_Creator_T2T)
        self.Save_Button.setGeometry(QtCore.QRect(240, 420, 75, 24))
        self.Save_Button.setObjectName("Save_Button")
        self.Remove_Pair_Button = QtWidgets.QPushButton(parent=Set_Creator_T2T)
        self.Remove_Pair_Button.setGeometry(QtCore.QRect(210, 150, 75, 24))
        self.Remove_Pair_Button.setObjectName("Remove_Pair_Button")

        self.retranslateUi(Set_Creator_T2T)
        QtCore.QMetaObject.connectSlotsByName(Set_Creator_T2T)

    def retranslateUi(self, Set_Creator_T2T):
        _translate = QtCore.QCoreApplication.translate
        Set_Creator_T2T.setWindowTitle(_translate("Set_Creator_T2T", "Wort-zu-Definition-Set hinzufügen"))
        self.Term_Label.setText(_translate("Set_Creator_T2T", "Begriff:"))
        self.Def_Label.setText(_translate("Set_Creator_T2T", "Definition:"))
        self.Add_Pair_Button.setText(_translate("Set_Creator_T2T", "Hinzufügen"))
        self.Close_Button.setText(_translate("Set_Creator_T2T", "Abbrechen"))
        self.Save_Button.setText(_translate("Set_Creator_T2T", "Speichern"))
        self.Remove_Pair_Button.setText(_translate("Set_Creator_T2T", "Widerrufen"))
