# Form implementation generated from reading ui file 'Set_Creator_LText.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Set_Creator_LText(object):
    def setupUi(self, Set_Creator_LText):
        Set_Creator_LText.setObjectName("Set_Creator_LText")
        Set_Creator_LText.resize(600, 500)
        self.LText_textEdit = QtWidgets.QTextEdit(parent=Set_Creator_LText)
        self.LText_textEdit.setGeometry(QtCore.QRect(20, 50, 561, 181))
        self.LText_textEdit.setObjectName("LText_textEdit")
        self.LText_label = QtWidgets.QLabel(parent=Set_Creator_LText)
        self.LText_label.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.LText_label.setObjectName("LText_label")
        self.cancel_button = QtWidgets.QPushButton(parent=Set_Creator_LText)
        self.cancel_button.setGeometry(QtCore.QRect(500, 450, 75, 24))
        self.cancel_button.setObjectName("cancel_button")
        self.save_button = QtWidgets.QPushButton(parent=Set_Creator_LText)
        self.save_button.setGeometry(QtCore.QRect(410, 450, 75, 24))
        self.save_button.setObjectName("save_button")
        self.LTerms_textEdit = QtWidgets.QTextEdit(parent=Set_Creator_LText)
        self.LTerms_textEdit.setGeometry(QtCore.QRect(20, 270, 561, 71))
        self.LTerms_textEdit.setObjectName("LTerms_textEdit")
        self.LTerms_label = QtWidgets.QLabel(parent=Set_Creator_LText)
        self.LTerms_label.setGeometry(QtCore.QRect(20, 250, 121, 16))
        self.LTerms_label.setObjectName("LTerms_label")

        self.retranslateUi(Set_Creator_LText)
        QtCore.QMetaObject.connectSlotsByName(Set_Creator_LText)

    def retranslateUi(self, Set_Creator_LText):
        _translate = QtCore.QCoreApplication.translate
        Set_Creator_LText.setWindowTitle(_translate("Set_Creator_LText", "Lückentext hinzufügen"))
        self.LText_label.setText(_translate("Set_Creator_LText", "Lückentext einfügen:"))
        self.cancel_button.setText(_translate("Set_Creator_LText", "Abbrechen"))
        self.save_button.setText(_translate("Set_Creator_LText", "Speichern"))
        self.LTerms_label.setText(_translate("Set_Creator_LText", "Lernwörter eintragen:"))
