# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Downloads/Windows_Settings_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        SettingsWindow.setWindowIcon(icon)
        self.header_label = QtWidgets.QLabel(parent=SettingsWindow)
        self.header_label.setGeometry(QtCore.QRect(0, 0, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.header_label.setFont(font)
        self.header_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.placeholder_label = QtWidgets.QLabel(parent=SettingsWindow)
        self.placeholder_label.setGeometry(QtCore.QRect(0, 50, 400, 200))
        self.placeholder_label.setObjectName("placeholder_label")
        self.about_button = QtWidgets.QPushButton(parent=SettingsWindow)
        self.about_button.setGeometry(QtCore.QRect(15, 270, 370, 25))
        self.about_button.setObjectName("about_button")

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.header_label.setText(_translate("SettingsWindow", "Settings"))
        self.placeholder_label.setText(_translate("SettingsWindow", "Palceholder"))
        self.about_button.setText(_translate("SettingsWindow", "About Us"))
